server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/cart/**, /orders/**

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**, /auth/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
